name: CD

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    uses: codeready-toolchain/devcluster/.github/workflows/test.yml

  deploy:
    name: Deploy
    uses: codeready-toolchain/devcluster/.github/workflows/deploy.yml
