name: Test

on:
  workflow_call: 

env:
  GOPATH: /tmp/go
  GO_VERSION: 1.16.x

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: make build

    - name: Unit Tests
      run: make test

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.2

    - name: Integration Tests
      env:
        DEVCLUSTER_MONGODB_CONNECTION_STRING: mongodb://localhost:27017/devcluster-test?retryWrites=true&w=majority
      run: make test-integration

